server:
  port: 8080

spring:
  main:
    allow-bean-definition-overriding: true
  #  datasource:
  #    url: jdbc:mysql://127.0.0.1:3306/synergy?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
  #    username: root
  #    password: Abcdef@123456
  #    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapperxml/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: cn.laoniu.synergy.model # 注意：对应实体类的路径
logging:
  level:
    cn.laoniu.synergy.mapper: DEBUG
netty:
  port: 12345

